### ISSUE TITLE
Update crate random choice

### ISSUE THREAD

**Issue by StefanoD** [doomsplayer/sidekiq-rs#1]
Random Choice had some fixes, so you may want to update.

Modify in your toml

`random_choice = "0.3.0"`

to

`random_choice = "0.3"`

**Comment by dovahcrow** [comment]
![resolve](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQxhsdjQgvJa1d7DWGgFkiC6Szm6tmARfTa9vk9WkchMNLJj3p80dJESMo)
